{% set name = "pdspy" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53ba7b0687ec543c86b2dc883f3b2ff99ddb79d9b86166b388a35855258dbc89

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
    - cython
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base
    - astropy
    - h5py
    - mpi4py
    - emcee
    - dynesty
    - corner
    - galario
    - schwimmbad
    - scikit-learn

test:
  commands:
    - test -d ${PREFIX}
    - test -f ${PREFIX}/bin/disk_model.py

about:
  home: https://github.com/psheehan/pdspy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Radiative transfer modeling of protoplanetary disks

extra:
  recipe-maintainers:
    - psheehan
